name: Continuous Integration Workflow

# Trigger this workflow whenever a new PR is created on the main branch
on: 
    pull_request: 
        branches: master

# Set some defaults
defaults:
    run:
        shell: bash
        working-directory: ./
        
# Jobs run in parallel by default
jobs:
    test:
        name: 'Run unit tests'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: 'Checkout repository'

            - name: 'Install Dependencies'
              run: npm install

            - name: 'Run tests'
              run: npm test
    lint:                                     
        name: 'Run linter'                    
        runs-on: ubuntu-latest                
        steps:                                
            - uses: actions/checkout@v4       
              name: 'Checkout repository'     
                                              
            - name: 'Install Dependencies'    
              run: npm install                     
                                              
            - name: 'Run linter'              
              run: npm run lint     
